# Music Player Daemon Configuration
music_directory "/Users/_david/Workspace/Music"
db_file "/Users/_david/.config/mpd/database"
log_file "/Users/_david/.config/mpd/log"
pid_file "/Users/_david/.config/mpd/pid"
state_file "/Users/_david/.config/mpd/state"
sticker_file "/Users/_david/.config/mpd/sticker.sql"
restore_paused "yes"
playlist_directory "/Users/_david/.config/mpd/playlists"
bind_to_address "127.0.0.1"
port "6600"
audio_output {
    type "osx"
    name "CoreAudio"
    mixer_type "software"
}
